Izersoft/Izersoft.WebUI/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Izersoft.Core.Domain;
using Izersoft.Service.Category;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Izersoft.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private ICategoryService _categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IActionResult Index()
        {
            return View(_categoryService.GetAllCategory());
        }

        public IActionResult CategoryDetail(int? id)
        {
            var model = _categoryService.GetCategoryById(id.Value);
            return View(model);
        }
        public IActionResult Delete()
        {
            return View();
        }
        public IActionResult Update(int? id)
        {
            var model = _categoryService.GetCategoryById(id.Value);
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(Category_ category)
        {
            _categoryService.UpdateCategory(category);
            return View(category);
        }

        public IActionResult Insert()
        {
            return View();
        }
    }
}

Izersoft/Izersoft.WebUI/Areas/Admin/Views/Category/CategoryDetail.cshtml
@model Izersoft.Core.Domain.Category_

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}

<div class="tab-content">
    <div class="tab-pane fade active show" id="basic-info-tab-pane" role="tabpanel" aria-labelledby="basic-info-tab">

        <div class="card p-6">

            <form>
                <div class="form-group">
                    <input type="text" class="form-control" aria-describedby="product name">
                    <label>Product Name</label>
                </div>

                <div class="form-group">
                    <textarea class="form-control" aria-describedby="product description" rows="5"></textarea>
                    <label>Product Description</label>
                </div>

                <div class="form-group">
                    <input type="text" class="form-control" aria-describedby="product categories">
                    <label>Categories</label>
                </div>

                <div class="form-group">
                    <input type="text" class="form-control" aria-describedby="product tags">
                    <label>Tags</label>
                </div>

            </form>
        </div>
    </div>
</div>

Izersoft/Izersoft.WebUI/Areas/Admin/Views/Category/Delete.cshtml
@model object

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}

Izersoft/Izersoft.WebUI/Areas/Admin/Views/Category/Index.cshtml
@model System.Collections.Generic.IList<Izersoft.Core.Domain.Category_>
@{
    ViewData["Title"] = "New";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="content-wrapper">
    <table id="example" class="cell-border compact stripe" style="width: 100%; font-size: 14px;">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Removed</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.CategoryId</td>
                    <td>@item.CategoryName</td>
                    <td>@item.IsDelete</td>
                    <td class="text-center">
                        <a asp-action="Delete" asp-route-id="@item.CategoryId" class="btn btn-primary btn-sm"><i class="icon-close-outline"></i></a>
                        <a asp-action="Update" asp-route-id="@item.CategoryId" class="btn btn-primary btn-sm"><i class="icon-pen"></i></a>
                        <a asp-action="Insert" asp-route-id="@item.CategoryId" class="btn btn-primary btn-sm"><i class="icon-plus-outline"></i></a>
                    </td>
                </tr>
            }


        </tbody>
    </table>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>

Izersoft/Izersoft.WebUI/Areas/Admin/Views/Category/Insert.cshtml
@model object

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}

<h2>title</h2>

Izersoft/Izersoft.WebUI/Areas/Admin/Views/Category/Update.cshtml
@model Izersoft.Core.Domain.Category_

@{
    ViewBag.Title = "title";
    Layout = "_AdminLayout";
}
@section Scripts{
    <link href="~/admin/css/snippet.css" rel="stylesheet" />
    <link href="~/admin/css/snippet-styles.css" rel="stylesheet" />
    <script>
        (function () {
            'use strict';
            var el = document.createElement('script');
            el.setAttribute('async', 'async');
            el.setAttribute('defer', 'defer');
            if (typeof Symbol === 'function' && typeof Symbol() === 'symbol') {
                el.src = "../js/ckeditor/app.js";
            } else {
                el.src = "../js/ckeditor/app-polyfill.js";
            }
            document.getElementsByTagName('head')[0].appendChild(el);
        })();
    </script>
    <script async="async" defer="defer" src="~/admin/js/ckeditor/app.js"></script>
}

<div class="tab-content">
    <div class="tab-pane fade active show" id="basic-info-tab-pane" role="tabpanel" aria-labelledby="basic-info-tab">

        <div class="card p-6">
            <form asp-action="Update" asp-controller="Category">
                <div class="form-group">

                    <input value="@Model.CategoryId" type="number" class="form-control" aria-describedby="category name" disabled>
                    <input asp-for="@Model.CategoryId" hidden>
                    <label>Category Id</label>
                </div>
                <div class="form-group">
                    <input id="CategoryName" name="CategoryName" value="@Model.CategoryName" type="text" class="form-control" aria-describedby="category name">
                    <label>Category Name</label>
                </div>

                <div class="input-group mb-8">

                    <span class="input-group-addon pt-4">Is Still Active?</span>
                    <input id="IsDelete" name="IsDelete" @(Model.IsDelete == true ? "" : "checked") type="checkbox" class="form-control" aria-describedby="Is Active?">
                </div>

                <div class="form-group">
                    <section class="main__content formatted">
                        <div class="live-snippet">
                            <div id="snippet-balloon-editor" class="ck ck-content ck-editor__editable ck-rounded-corners ck-blurred ck-editor__editable_inline" contenteditable="true" role="textbox" aria-label="Rich Text Editor, main">
                                @Html.Raw(Model.CategoryContent)
                            </div>
                        </div>
                    </section>
                    <script src="~/admin/js/ckeditor/snippet.js"></script>
                    <div class="ck ck-reset_all ck-body ck-rounded-corners">
                        <div class="ck ck-balloon-panel ck-balloon-panel_arrow_n ck-balloon-panel_with-arrow ck-toolbar-container" style="top: 762.422px; left: 775px;">
                        </div>
                    </div>

                    <textarea id="CategoryContent" name="CategoryContent" hidden></textarea>


                </div>

                <input type="submit" id="tik" value="Save Changes" />
                <script type="text/javascript">
                        $(document).ready(function (e) {
                            $("#tik").click(function () {
                                var htmldata = document.getElementById("snippet-balloon-editor").innerHTML
                                $("#CategoryContent").val(htmldata);
                            });
                        });
                </script>
            </form>
        </div>
    </div>
</div>