Izersoft/Izersoft.WebUI/ViewComponents/CategoryListViewComponent.cs
using Izersoft.Service.Category;
using Microsoft.AspNetCore.Mvc;

namespace Izersoft.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            return View(_categoryService.GetAllCategory());
        }
    }
}

Izersoft/Izersoft.WebUI/Views/Shared/_Footer.cshtml
<footer class="short" id="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="newsletter">
                    <h4>
                        <strong>Izersoft</strong> Hakkında
                    </h4>
                    <p>
                        Izersoft, İzmir merkezli bir kuruluş olup ağırlıklı olarak Ege Bölgesi,Akdeniz ve Marmara Bölgesi olmak üzere
                        tüm Türkiye geneline hizmet vermektedir.
                        <a href="/Home/About" class="btn-flat btn-xs">
                            Devamı
                            <i class="fa fa-arrow-right"></i>
                        </a>
                    </p>
                </div>
                <hr class="light">
                <div class="row">
                    <div class="col-lg-3">
                        <h5>HİZMETLERİMİZ</h5>
                        <ul class="list list-icons list-icons-sm">
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/CorporateWebSite">Kurumsal Web Sitesi</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/Ecommerce">E-Ticaret Sistemleri</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/MobileApp">Kurumsal Mobil Uygulama</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/InternetOfThings">Nesnelerin İnterneti</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/DomainTescil">Domain Tescil / Hosting Hizmeti</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/AutomationSystem">Otomasyon Sistemleri</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3">
                        <h5>HİZMETLERİMİZ</h5>
                        <ul class="list list-icons list-icons-sm">
                            <li><i class="fas fa-caret-right"></i> <a href="#">Kurumsal Eğitim Seminerleri</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/CorporateIdentityWork">Kurumsal Kimlik Çalışmaları</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/SpecialSoftwareSolution">Özel Yazılım Çözümleri</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/InternetAdvertisement">İnternet Reklamcılığı</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/SocialMediaManagement">Sosyal Medya Yöneticiliği</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="page-custom-header.html">Reklamcılık ve Matbaa İşlemleri</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3">
                        <h5>KURUMSAL</h5>
                        <ul class="list list-icons list-icons-sm">
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/About">Hakkımızda</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/MissionVision">Misyon | Vizyon</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/OurTeam">Ekibimiz</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/HumanResources">İnsan Kaynakları</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/SocialMedia">Sosyal Medya</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3">
                        <h5>REFERANSLARIMIZ</h5>
                        <ul class="list list-icons list-icons-sm">
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/WorkedWith">Kimlerle Çalıştık ?</a></li>
                            <li><i class="fas fa-caret-right"></i> <a href="/Home/OurWorks">Neler Yaptık ?</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <h5 class="mb-2">İLETİŞİM</h5>
                <span class="phone">(530) 410 25 86</span>
                <ul class="list list-icons mt-4">
                    <li><i class="fas fa-map-marker-alt"></i> <strong>Adres:</strong> Etiler Mah. 1266 Sk. No:10 K:6 D:601 Basmane | Konak | İZMİR</li>
                    <li><i class="far fa-envelope"></i> <strong>Email:</strong> <a href="mailto:info@izersoft.com ">info@izersoft.com.tr </a></li>
                </ul>
                <ul class="social-icons mt-4">
                    <li class="social-icons-facebook"><a href="http://www.facebook.com/" target="_blank" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>
                    <li class="social-icons-twitter"><a href="http://www.twitter.com/" target="_blank" title="Twitter"><i class="fab fa-twitter"></i></a></li>
                    <li class="social-icons-linkedin"><a href="http://www.linkedin.com/" target="_blank" title="Linkedin"><i class="fab fa-linkedin-in"></i></a></li>
                    <li class="social-icons-instagram"><a href="http://www.instagram.com/" target="_blank" title="instagram"><i class="fab fa-instagram"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-11">
                    <p>© Copyright 2018. All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

Izersoft/Izersoft.WebUI/Views/Shared/_Header.cshtml
<header id="header" class="header-narrow header-transparent header-transparent-bottom-border" data-plugin-options="{'stickyEnabled': true, 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': true, 'stickyStartAt': 1, 'stickySetTop': '1'}">
    <div class="header-body">
        <div class="header-container container">
            <div class="header-row">
                <div class="header-column">
                    <div class="header-row">
                        <div class="header-logo">
                            <a href="/Home/Index">
                                <img alt="Izersoft" height="40" src="~/img/logo5.png">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="header-column justify-content-end">
                    <div class="header-row">
                        <div class="header-nav header-nav-stripe">
                            <div class="header-nav-main header-nav-main-square header-nav-main-effect-2 header-nav-main-sub-effect-1">
                                <nav class="collapse">
                                    <ul class="nav nav-pills" id="mainNav">
                                        <li class="dropdown">
                                            <a class="dropdown-item" href="/Home/Index">
                                                Ana Sayfa
                                            </a>
                                        </li>

                                        <li class="dropdown">
                                            <a class="dropdown-item dropdown-toggle" href="#">
                                                HİZMETLERİMİZ
                                            </a>
                                            @await Component.InvokeAsync("CategoryList")
                                        </li>
                                        <li class="dropdown">
                                            <a class="dropdown-item dropdown-toggle" href="#">
                                                ARGE
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="/Home/ArgeTeam" class="dropdown-item" routerLink="arge-ekibimiz">
                                                        ARGE Ekibimiz
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="/Home/ArgeWorks" class="dropdown-item" routerLink="arge-calismalarimiz">
                                                        ARGE Çalışmalarımız
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a class="dropdown-item dropdown-toggle" href="#">
                                                KURUMSAL
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="/Home/About" class="dropdown-item" routerLink="hakkimizda">
                                                        Hakkımızda
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="/Home/MissionVision" class="dropdown-item" routerLink="misyon-vizyon">
                                                        Misyonumuz - Vizyonumuz
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="/Home/OurTeam" class="dropdown-item" routerLink="ekibimiz">
                                                        Ekibimiz
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="/Home/HumanResources" class="dropdown-item" routerLink="insan-kaynaklari">
                                                        İnsan Kaynakları
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a class="dropdown-item dropdown-toggle" href="#">
                                                REFERANSLARIMIZ
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="/Home/WorkedWith" class="dropdown-item" routerLink="arge-ekibimiz">
                                                        Kimlerle Çalıştık ?
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="/Home/OurWorks" class="dropdown-item" routerLink="arge-calismalarimiz">
                                                        Neler Yaptık ?
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a class="dropdown-item " routerLink="iletisim" href="/Home/Contact">
                                                İLETİŞİM
                                            </a>
                                        </li>

                                    </ul>

                                    <ul class="nav nav-pills" id="mainNav">
                                        <li class="dropdown dropdown-mega dropdown-mega-shop" id="headerShop">
                                            <a class="dropdown-item" href="/Home/Basket">
                                                <i class="fas fa-shopping-cart"></i>(1) $299
                                            </a>

                                        </li>
                                        <li class="dropdown dropdown-mega dropdown-mega-signin signin" id="headerAccount">
                                            <a class="dropdown-item " href="/Home/Login">
                                                <i class="fas fa-user"></i> Giriş
                                            </a>

                                        </li>
                                    </ul>

                                </nav>
                            </div>



                           
                                                
                                    


                           
                            <button class="btn header-btn-collapse-nav" data-toggle="collapse" data-target=".header-nav-main nav">
                                <i class="fas fa-bars"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

Izersoft/Izersoft.WebUI/Views/Shared/_Imports.cshtml
<script src="~/vendor/jquery/jquery.min.js"></script>
<script src="~/vendor/jquery.appear/jquery.appear.min.js"></script>
<script src="~/vendor/jquery.easing/jquery.easing.min.js"></script>
<script src="~/vendor/jquery-cookie/jquery-cookie.min.js"></script>
<script src="~/vendor/popper/umd/popper.min.js"></script>
<script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="~/vendor/common/common.min.js"></script>
<script src="~/vendor/jquery.validation/jquery.validation.min.js"></script>
<script src="~/vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.min.js"></script>
<script src="~/vendor/jquery.gmap/jquery.gmap.min.js"></script>
<script src="~/vendor/jquery.lazyload/jquery.lazyload.min.js"></script>
<script src="~/vendor/isotope/jquery.isotope.min.js"></script>
<script src="~/vendor/owl.carousel/owl.carousel.min.js"></script>
<script src="~/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="~/vendor/vide/vide.min.js"></script>

<!-- Theme Base, Components and Settings -->
<script src="~/js/theme.js"></script>

<!-- Current Page Vendor and Views -->
<script src="~/vendor/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
<script src="~/vendor/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
<script src="~/vendor/circle-flip-slideshow/js/jquery.flipshow.min.js"></script>
<script src="~/js/views/view.home.js"></script>

<!-- Theme Custom -->
<script src="~/js/custom.js"></script>

<!-- Theme Initialization Files -->
<script src="~/js/theme.init.js"></script>

<!-- Examples -->
<script src="~/js/examples/examples.lightboxes.js"></script>

Izersoft/Izersoft.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">


    <meta name="keywords" content="HTML5 Template">
    <meta name="description" content="Porto - Responsive HTML5 Template">
    <meta name="author" content="okler.net">

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/img/favicon.ico" type="image/x-icon">

    <link rel="apple-touch-icon" href="~/img/apple-touch-icon.png">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

    <!-- Web Fonts  -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/vendor/font-awesome/css/fontawesome-all.css" rel="stylesheet" />
    <link href="~/vendor/animate/animate.min.css" rel="stylesheet" />
    <link href="~/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" />
    <link href="~/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/vendor/owl.carousel/assets/owl.theme.default.css" rel="stylesheet" />
    <link href="~/vendor/magnific-popup/magnific-popup.min.css" rel="stylesheet" />
    <!-- Theme CSS -->

    <link href="~/css/theme.css" rel="stylesheet" />
    <link href="~/css/theme-blog.css" rel="stylesheet" />
    <link href="~/css/theme-elements.css" rel="stylesheet" />
    <link href="~/css/theme-shop.css" rel="stylesheet" />

    <!-- Current Page CSS -->
    <link href="~/vendor/rs-plugin/css/settings.css" rel="stylesheet" />
    <link href="~/vendor/rs-plugin/css/layers.css" rel="stylesheet" />
    <link href="~/vendor/rs-plugin/css/navigation.css" rel="stylesheet" />
    <link href="~/vendor/circle-flip-slideshow/css/component.css" rel="stylesheet" />
    <!-- Skin CSS -->
    <link rel="stylesheet" href="~/css/skins/default.css">

    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="~/css/custom.css">

    <!-- Head Libs -->
    <script src="~/vendor/modernizr/modernizr.min.js"></script>

    <!-- Demo CSS -->
    <!--MAP SECTION-->

    <script src="~/js/map-script.js"></script>
    <script src="http://maps.google.com/maps/api/js?key=AIzaSyBKS14AnP3HCIVlUpPKtGp7CbYuMtcXE2o"></script>

</head>
<body>
    <div class="body">
        @{await Html.RenderPartialAsync("_Header");}
        @RenderBody()
        @{await Html.RenderPartialAsync("_Footer");}
    </div>
    @{await Html.RenderPartialAsync("_Imports");}
</body>
</html>

Izersoft/Izersoft.WebUI/Views/Shared/_MenuSpacing.cshtml
<div style="height:60px;background-color:#696969"></div>